#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
lit_review builder — automation run #12 (2026-08-03)
Re-anchors a faithful corpus from the 9 live complementary PubMed queries (a–i)
executed via mcp__paper-search-mcp__search_pubmed (DeferExecuteTool), max_results=15, sort=relevance.
Dedupes by PMID, screens in-scope thyroid papers, tags relevance + dimensions,
and writes search_results_latest.json with a new-vs-run#11 delta section.
"""
import json, os, datetime

LR = r"D:\paperwork\lit_review"
OUT = os.path.join(LR, "search_results_latest.json")
RUN_DATE = "2026-08-03"

# ---- 9 live queries (verbatim) -------------------------------------------------
QUERIES = {
    "a": "thyroid cancer lymph node metastasis biomarker gene signature",
    "b": "thyroid cancer invasion metastasis molecular mechanism",
    "c": "thyroid cancer lymph node metastasis machine learning deep learning prediction model",
    "d": "thyroid cancer metastasis tumor immune microenvironment",
    "e": "thyroid cancer metastasis single cell RNA sequencing",
    "f": "thyroid cancer metastasis spatial transcriptomics spatial multi-omics",
    "g": "thyroid cancer prognosis recurrence distant metastasis risk model",
    "h": "thyroid cancer metastatic stemness subpopulation",
    "i": "thyroid cancer metabolic reprogramming metastasis",
}

# ---- Raw rows captured from the 9 live MCP calls (title, pmid, doi) ------------
# Each tuple: (query_tag, pmid, title, doi, is_thyroid, relevance, dims, disease,
#              data_source, method, endpoint, main_finding, validation, limitation, gap, future)
# dims use 2-letter codes: MO=分子机制, IM=免疫微环境, SC=单细胞, SP=空间组学,
#                           AL=算法方法, PR=预后转移, ME=代谢重编程, ST=转移干性
# Off-topic (breast/gastric/HCC/pan-cancer/colorectal/TNBC) -> is_thyroid=False.
def R(q, pmid, title, doi, thy, rel, dims, dis, ds, meth, ep, mf, val, lim, gap, fut):
    return (q, pmid, title, doi, thy, rel, dims, dis, ds, meth, ep, mf, val, lim, gap, fut)

ROWS = [
 # ---- a: biomarker gene signature --------------------------------------------
 R("a","40110574","Identification of Novel Gene Signature Predicting Lymph Node Metastasis in Papillary Thyroid Cancer via Bioinformatics Analysis and in vitro Validation","10.2147/IJGM.S502480",True,"High",["MO","PR"],"PTC","TCGA+GEO(GSE60542)","WGCNA+LASSO","LNM","6-gene signature (COL8A2, MET, FN1, MPZL2, PDLIM4, CLDN10) predicts PTC LNM; all 6 validated in vitro.","in vitro (RT-qPCR/functional)","TCGA/GEO bulk only, no spatial/SC validation","No single-cell or spatial resolution of these drivers","Spatial validation of MET/FN1 axis"),
 R("a","40171809","A nomogram based on the 3-gene signature and clinical characteristics for predicting lymph node metastasis in papillary thyroid cancer","10.1177/18758592241311195",True,"High",["MO","PR"],"PTC","TCGA","WGCNA+LASSO+logistic","LNM","3-gene signature (IQGAP2, BTBD11, MT1G)+clinical nomogram AUC 0.802 train/0.718 val.","internal val cohort","single-cohort, modest val AUC","Mechanistic link between MT1G/BTBD11 and immune stroma","Functionally test IQGAP2/BTBD11 in LNM"),
 R("a","31711617","A novel gene panel for prediction of lymph-node metastasis and recurrence in patients with thyroid cancer","10.1016/j.surg.2019.06.058",True,"High",["MO","PR"],"PTC","TCGA","ML+logistic/Cox","LNM/recurrence","25-gene panel discriminates N0/N1 (sens 86%, spec 62%); HR 2.64 for DFS.","KM/Cox in TCGA","no wet-lab validation","Which genes drive metastasis biologically","Validate top drivers functionally"),
 R("a","33656532","A 4 Gene-based Immune Signature Predicts Dedifferentiation and Immune Exhaustion in Thyroid Cancer","10.1210/clinem/dgab132",True,"High",["IM","PR"],"DDTC/TC","TCGA+bulk","IRG signature+Cox","dediff/LNM","4 IRGs (PRKCQ, PLAUR, PSMD2, BMP7) predict dedifferentiation; linked to LNM & BRAFV600E.","2 validation cohorts","no spatial; bulk deconv","How IRGs drive immune exhaustion spatially","Spatial TIL/IRG mapping"),
 R("a","41368991","BRAF V600E in thyroid cancer: navigating prognostic uncertainty and therapeutic opportunity","10.1530/ETJ-25-0225",True,"Medium",["MO","PR"],"PTC/ATC/PDTC","review","review","prognosis","BRAF V600E debated prognostic value; drives MAPK, RAI-refractoriness; targetable.","review","review, not primary","Subtype-specific heterogeneity of V600E effect","Combine V600E with co-alterations"),
 R("a","35033555","A four-enhancer RNA-based prognostic signature for thyroid cancer","10.1016/j.yexcr.2022.113023",True,"Medium",["PR"],"TC","GTEx+TCGA","eRNA+Cox","prognosis/LNM","4 eRNAs (AC141930.1, NBDY, MEG3, AP002358.1) predict prognosis; linked to N stage.","TCGA+GEO","no wet-lab","Functional role of eRNAs in metastasis","Validate eRNA drivers"),
 R("a","30942873","Transcriptome Analyses Identify a Metabolic Gene Signature Indicative of Dedifferentiation of Papillary Thyroid Cancer","10.1210/jc.2018-02686",True,"Medium",["MO","ME","PR"],"PTC/DDTC","TCGA+GEO","metabolic signature+Cox","dediff/LNM","5 metabolic genes (LPCAT2, ACOT7, HSD17B8, PDE8B, ST3GAL1) mark dediff; linked to LNM.","3 cohorts","bulk only","Mechanism linking metabolism to dediff","SC/metabolic validation"),
 R("a","34595349","A two-microRNA signature predicts the progression of male thyroid cancer","10.1515/biol-2021-0099",True,"Low",["PR"],"male TC","TCGA","miRNA+Cox","recurrence","miR-451a & miR-16-1-3p independent prognostic in male TC.","TCGA","gender-specific, weak val","Mechanism of male-specific recurrence","Stratify by sex in models"),
 R("a","41701943","DNA Methylation-Based Risk Stratification and Classification of Pediatric Thyroid Carcinoma","10.1158/1078-0432.CCR-25-2109",True,"High",["MO","PR"],"pediatric TC","2 cohorts methylation","methylation classifiers","invasiveness/LNM","Methylation classifiers predict tumor invasiveness (nodal mets) & driver mutations in pediatric TC.","independent val cohort","limited LNM samples","Spatial epigenetics of invasion","Multi-omics pediatric atlas"),
 R("a","40741176","Development and validation of mRNA expression-based classifiers to predict low-risk thyroid tumors","10.3389/fendo.2025.1600815",True,"High",["AL","PR"],"Bethesda III-VI","Afirma GSC+retrospective","ML classifiers","invasion/LNM","mRNA classifiers rule out invasion (NPV 97.6%) & LNM (NPV 98.6%) preoperatively.","retrospective val (259)","retrospective; vendor cohort","Prospective multi-site validation","Prospective deployment"),
 R("a","39497824","Coagulation-related genes for thyroid cancer prognosis, immune infiltration, staging, and drug sensitivity","10.3389/fimmu.2024.1462755",True,"Medium",["IM","PR"],"THCA","TCGA","LASSO+Cox","LLNM/prognosis","D-dimer predicts LLNM (AUC 0.656); 8 prognostic CRGs model.","qPCR","modest AUC; bulk","Mechanism linking coagulation to mets","Functional coagulation axis"),
 R("a","41656803","A multi-molecular predictive model for lymph node metastasis in papillary thyroid carcinoma based on machine learning algorithms","10.11817/j.issn.1672-7347.2025.250216",True,"High",["AL","MO","PR"],"PTC","TCGA (507)","DESeq2/edgeR/Limma/WGCNA+LASSO+ML","LNM","11-gene signature (incl. FN1) Model 2 AUC 0.802 train/0.793 val; stable across 6 ML algos.","TCGA val; sex-strat","TCGA only; no external","External multi-center validation","Externalize FN1-based model"),
 R("a","35255661","Transcriptomic Analysis of Papillary Thyroid Cancer: A Focus on Immune-Subtyping, Oncogenic Fusion, and Recurrence","10.21053/ceo.2021.02215",True,"Medium",["IM","PR"],"PTC","SNUH+SNUH+TCGA","RNA-seq+sc","recurrence/immune","Recurrence linked to CD8+/Th1 signatures; CTLA4/IDO1/LAG3/PDCD1 in low-TDS; HOXD9 recurrence marker.","TCGA val","single-country","Functional role of HOXD9","Validate HOXD9"),
 R("a","40977710","Multi-omics analysis and metastasis risk factor prediction in N1b stage PTMC: insights into immune infiltration and therapeutic implications","10.3389/fimmu.2025.1620085",True,"High",["MO","IM","PR"],"PTMC N1b","638 PTMC+sc/omics","ML+WGCNA+MLP","lateral LNM","NLR model (AUC 0.852); 4-gene signature (ALDH1A3, CTXN1, MGAT3, TMEM163) AUC 0.857; CD8+ T reduced.","IHC+MLP","retrospective","Therapeutic targeting of signature","Prospective N1b risk"),
 R("a","37274228","Identification of key immune genes related to lymphatic metastasis of papillary thyroid cancer via bioinformatics analysis and experimental validation","10.3389/fonc.2023.1181325",True,"High",["IM","MO"],"PTC","TCGA+ImmPort","WGCNA+LASSO/RF","LNM","3 hub immune genes (PTGS2, MET, ICAM1) upregulated in LNM; model AUC 0.83; IHC validated.","IHC validation","bulk only","Spatial immune landscape of MET/ICAM1","Spatial IHC/ST"),
 # ---- b: invasion/metastasis mechanism ---------------------------------------
 R("b","39810624","Single-cell RNA-sequencing and spatial transcriptomic analysis reveal a distinct population of APOE- cells yielding pathological lymph node metastasis in papillary thyroid cancer","10.1002/ctm2.70172",True,"High",["SC","SP","MO","AL"],"PTC","scRNA+ST","scRNA+ST+ML","LNM","APOE- tumor subpop drives cervical LNM & poor prognosis via ABCA1-LXR; 13-gene ML LNM signature.","in vivo/in vitro+ST","single-center SC/ST","Target APOE- subpopulation therapeutically","APOE- targeted therapy"),
 R("b","40456735","Neuro-immune crosstalk in cancer: mechanisms and therapeutic implications","10.1038/s41392-025-02241-8",False,"Low",["IM"],"pan-cancer","review","review","TIME","Nervous system modulates TIME; tumor cells mimic neuronal anti-inflammatory profiles.","review","pan-cancer review","Thyroid-specific neuro-immune axis","Thyroid neural niche"),
 R("b","17133106","Molecular mechanisms involved in differentiated thyroid cancer invasion and metastasis","10.2147",True,"Medium",["MO"],"DTC","review","review","invasion/mets","RAS-RAF-ERK & PI3K/PDK1/Akt; EMT & collective migration reactivated.","review","old review (2007)","Modern single-cell resolution of EMT","SC EMT trajectory"),
 R("b","39719645","The role of MAPK pathway in gastric cancer: unveiling molecular crosstalk and therapeutic prospects","10.1186/s12967-024-05998-8",False,"Low",["MO"],"gastric","review","review","mets","MAPK in gastric carcinogenesis.","review","off-topic (gastric)","-","-"),
 R("b","37835455","Thyroid Cancer: Focus on Invasion and Metastasis Mechanisms, Therapeutic Target and Drug Treatment","10.3390/cancers15194762",True,"Medium",["MO","PR"],"TC","review","review","invasion/mets","Reviews invasion/metastasis mechanisms & therapeutic targets in TC.","review","review","Mechanistic gaps in therapy resistance","Targeted therapy combos"),
 R("b","38935111","The association between immune cells and breast cancer: insights from Mendelian randomization and meta-analysis","10.1097/JS9.0000000000001840",False,"Low",["IM"],"breast","MR+meta","immune","prognosis","Two immune phenotypes protect against BC.","MR+meta","off-topic (breast)","-","-"),
 R("b","35973989","DDX39B drives colorectal cancer progression by promoting the stability and nuclear translocation of PKM2","10.1038/s41392-022-01096-7",False,"Low",["MO","ME"],"CRC","in vitro/in vivo","PKM2","mets","DDX39B stabilizes PKM2 -> Warburg in CRC.","in vitro/in vivo","off-topic (CRC)","-","-"),
 R("b","38172081","IRS1 promotes thyroid cancer metastasis through EMT and PI3K/AKT pathways","10.1111/cen.15005",True,"High",["MO"],"TC","131 tissues+RNAseq","IHC+RNAseq","distant mets","IRS1 high in TC, linked to distant mets/advanced stage; drives mets via EMT & PI3K/AKT.","in vitro","no SC","Therapeutic targeting of IRS1","IRS1 inhibitor"),
 R("b","40651298","An integrative analysis reveals mechanisms of Prunella vulgaris in thyroid cancer metastasis","10.1016/j.phymed.2025.157051",True,"Medium",["MO","ME"],"PTC LNM","RNAseq+TCMSP","ML+hub gene","LNM","β-sitosterol targets ADRB2, inhibits PTC mets via mitochondrial dysfunction.","in vitro","herb-focused","ADRB2 mechanism in LNM","ADRB2 validation"),
 R("b","34916087","Molecular mechanisms of thyroid cancer: A competing endogenous RNA (ceRNA) point of view","10.1016/j.biopha.2021.112251",True,"Low",["MO"],"TC","review","review","mets/EMT","ceRNA networks deregulated in TC progression/EMT.","review","review","Specific ceRNA causal tests","ceRNA functional"),
 R("b","29546880","Cell motility in cancer invasion and metastasis: insights from simple model organisms","10.1038/nrc.2018.15",False,"Low",["MO"],"pan-cancer","review","review","motility","Model organisms reveal motility mechanisms; thyroid kinase inhibitors from flies.","review","off-topic (general)","-","-"),
 R("b","37664917","Myc-Associated Zinc Finger Protein Promotes Metastasis of Papillary Thyroid Cancer","10.31083/j.fbl2808162",True,"Medium",["MO"],"PTC","TCGA+IHC","IHC+functional","mets","MAZ high promotes PTC migration/invasion via EMT; FN1 negatively correlated.","in vitro","no SC","MAZ-FN1 axis detail","MAZ functional"),
 R("b","40855521","NSUN2-tRNAVal-CAC-axis-regulated codon-biased translation drives triple-negative breast cancer glycolysis and progression","10.1186/s11658-025-00781-z",False,"Low",["ME"],"TNBC","in vitro/in vivo","tRNA m5C","glycolysis","NSUN2 drives TNBC glycolysis.","in vitro/in vivo","off-topic (TNBC)","-","-"),
 R("b","39301627","Molecular mechanisms and clinicopathological characteristics of inhibin betaA in thyroid cancer metastasis","10.3892/ijmm.2024.5423",True,"Medium",["MO"],"TC","GEO/TCGA+in vivo","transfect+zf/mouse","mets","INHBA promotes TC migration/invasion via RhoA/LIMK/cofilin; knockdown attenuates mets.","in vivo","no SC","Therapeutic INHBA blockade","INHBA inhibitor"),
 R("b","17940185","BRAF mutation in papillary thyroid cancer: pathogenic role, molecular bases, and clinical implications","10.2147",True,"Medium",["MO","PR"],"PTC","review","review","progression/recurrence","BRAF V600E associated with progression/recurrence; downregulates TSGs & iodide genes.","review","old review (2007)","Subtype heterogeneity","Combine with co-alts"),
 # ---- c: ML/DL prediction ------------------------------------------------------
 R("c","40750786","Explainable multimodal deep learning for predicting thyroid cancer lateral lymph node metastasis using ultrasound imaging","10.1038/s41467-025-62042-z",True,"High",["AL"],"PTC LLNM","29,615 pts/7 centers","LLNM-Net (bidir-attn DL)","LLNM","LLNM-Net AUC 0.944, 84.7% acc in multicenter testing; beats experts (64.3%).","7-center external","retrospective; US-only","Prospective deployment + cost-effectiveness","Prospective LLNM-Net"),
 R("c","39137488","Non-invasive prediction of axillary lymph node dissection exemption in breast cancer patients post-neoadjuvant therapy","10.1016/j.breast.2024.103786",False,"Low",["AL"],"breast","DCE-MRI","LightGBM/SVM/RF/MLP","axillary LNM","SVM Data Amalgamation AUC 0.986 for ypN0 in BC.","10-fold CV","off-topic (breast)","-","-"),
 R("c","38990290","Artificial intelligence-based multi-modal multi-tasks analysis reveals tumor molecular heterogeneity, predicts preoperative lymph node metastasis and prognosis in papillary thyroid carcinoma","10.1097/JS9.0000000000001875",True,"High",["AL","MO","SC"],"PTC","1011 PTC (TCGA+real-world+scRNA)","DL multimodal","LNM/DFS","4 molecular subtypes; DL AUC 0.86 train/0.84 val/0.83 real-world for LNM & DFS.","TCGA external val","retrospective, single real-world center","Prospective multi-center DL","Prospective DL"),
 R("c","37574759","Deep learning prediction model for central lymph node metastasis in papillary thyroid microcarcinoma based on cytology","10.1111/cas.15930",True,"Medium",["AL"],"PTMC CLNM","42 FNA","CNN","CLNM","DL on FNA liquid-based prep AUC 0.850; surpasses clinical exam.","small (42)","tiny n","Larger FNA cytology cohort","Scale FNA-DL"),
 R("c","40771372","Development and validation of a prediction model for lymph node metastasis in thyroid cancer: integrating deep learning and radiomics features from intra- and peri-tumoral regions","10.21037/gs-2025-50",True,"High",["AL"],"PTC CLNM","405 pts/2 centers","radiomics+DL fusion SVM","CLNM","Fusion SVM AUC 0.897 internal/0.881 external; best of radiomics/DL.","external test","US-only","Prospective + other modalities","Prospective fusion"),
 R("c","31746687","Lymph Node Metastasis Prediction from Primary Breast Cancer US Images Using Deep Learning","10.1148/radiol.2019190372",False,"Low",["AL"],"breast","US images","CNN (Inception/ResNet)","axillary LNM","Inception V3 AUC 0.89 in BC independent test.","independent test","off-topic (breast)","-","-"),
 R("c","39421056","Radiomics and deep learning for large volume lymph node metastasis in papillary thyroid carcinoma","10.21037/gs-24-308",True,"Medium",["AL"],"PTC LVLNM","854 pts/3 centers","radiomics+DL (8 ML + 5 DL)","LVLNM","Thy-DL-Radiomics AUC 0.839 internal/0.789 external for large-volume LNM.","external val","LVLNM subset only","Generalize to all CLNM","Broaden LVLNM model"),
 R("c","36750791","Deep learning-based multifeature integration robustly predicts central lymph node metastasis in papillary thyroid cancer","10.1186/s12885-023-10598-8",True,"Medium",["AL"],"PTC CLNM","488 FNA","CNN+logistic","CLNM","CNN AUC 0.89 train/0.78 test; nomogram 0.778.","test set","single center","External validation","External CNN"),
 R("c","38563008","Predicting central cervical lymph node metastasis in papillary thyroid microcarcinoma using deep learning","10.7717/peerj.16952",True,"Low",["AL"],"PTMC CLNM","611 US","DL+clinical","CLNM","DL US AUC 0.65; clinical 0.64; combined 0.63.","test set","weak performance","Better features/modalities","Improve PTMC-DL"),
 R("c","39742800","Predicting lymph node metastasis in thyroid cancer: systematic review and meta-analysis on the CT/MRI-based radiomics and deep learning models","10.1016/j.clinimag.2024.110392",True,"High",["AL"],"TC","16 studies (meta)","meta","LNM","Pooled AUC 0.86 internal/0.87 train; DL sens 80.8%/spec 78.7% > radiomics; clinical data helps (p=0.037).","meta (16)","heterogeneity","Standardized reporting/prospective","Prospective harmonization"),
 R("c","39682228","Multimodal MRI Deep Learning for Predicting Central Lymph Node Metastasis in Papillary Thyroid Cancer","10.3390/cancers16234042",True,"Medium",["AL"],"PTC CLNM","105 MRI","AMMCNet (CNN)","CLNM","DL fusion AUC 0.891 > best ML 0.863.","internal test","small, MRI-only","External multi-center MRI","External MRI-DL"),
 R("c","40778281","A novel deep learning model based on multimodal contrast-enhanced ultrasound dynamic video for predicting occult lymph node metastasis in papillary thyroid carcinoma","10.3389/fendo.2025.1634875",True,"Medium",["AL"],"PTC OLNM","396 US/CEUS","DL video (5 arch)","OLNM","DL_combined AUC 0.926 train/0.734 test.","test set","test drop-off","Larger CEUS video cohort","Scale CEUS-DL"),
 R("c","37178202","Artificial intelligence-based prediction of cervical lymph node metastasis in papillary thyroid cancer with CT","10.1007/s00330-023-09700-2",True,"High",["AL"],"PTC CLNM","multicenter CT","DenseNet+CBAM+ML","CLNM","AI AUC 0.84 internal/0.81 external; improves radiologist spec 9-15%.","external test","CT-only","Prospective + other centers","Prospective CT-AI"),
 R("c","41061579","SCLResNet and DSAF: A self-supervised contrastive learning and deep self-attention fusion-based multimodal network for predicting central lymph node metastasis in papillary thyroid carcinoma","10.1016/j.artmed.2025.103280",True,"Medium",["AL"],"PTC CLNM","US+CT","SCLResNet+DSAF","CLNM","AUC 0.863 internal/0.839 external; adds PVAT.","external test","retrospective","Prospective multi-modal","Prospective fusion"),
 R("c","41237514","A multi-task deep learning framework for intraoperative diagnosis of thyroid cancer metastasis using whole slide images","10.1016/j.ijmedinf.2025.106176",True,"High",["AL"],"PTC LNM","569 WSIs/2 centers","CLAM (MIL)","LNM/T-stage/localization","CLAM AUC 0.85 LNM, 0.65 T-stage, 0.71 localization; cross-center.","10-fold MC CV","weak T-stage/localization","Improve localization subtask","Refine CLAM tasks"),
 # ---- d: tumor immune microenvironment ----------------------------------------
 R("d","32626535","Immune Microenvironment of Thyroid Cancer","10.7150/jca.44506",True,"Medium",["IM"],"TC","review","review","TIME","Reviews immune cells, soluble mediators, checkpoints, evasion & immunotherapy in TC.","review","review","Spatial immune phenotyping","Spatial TIL"),
 R("d","36975413","Tumor-Infiltrating Immune Cell Landscapes in the Lymph Node Metastasis of Papillary Thyroid Cancer","10.3390/curroncol30030200",True,"High",["IM"],"PTC LNM","TCGA+bulk","CIBERSORT/CIBERSORTx","LNM","LNM linked to activated DC/M0 macro (up) & NK/eosinophil (down); TG mut->M2, HRAS mut->DC.","TCGA","bulk deconv","Spatial immune niches in LNM","Spatial immune"),
 R("d","39221971","Tryptophan 2,3-dioxygenase-positive matrix fibroblasts fuel breast cancer lung metastasis via kynurenine-mediated ferroptosis resistance","10.1002/cac2.12608",False,"Low",["IM","SC"],"breast","scRNA+in vivo","scRNA","lung mets","TDO2+ MF drive BC lung mets via KYN/ferroptosis.","in vivo/scRNA","off-topic (breast)","-","-"),
 R("d","38935111","The association between immune cells and breast cancer: insights from Mendelian randomization and meta-analysis","10.1097/JS9.0000000000001840",False,"Low",["IM"],"breast","MR+meta","immune","prognosis","(duplicate entry; breast)","MR+meta","off-topic","-","-"),
 R("d","37173925","The Tumor Microenvironment and the Estrogen Loop in Thyroid Cancer","10.3390/cancers15092458",True,"Medium",["IM"],"TC","review","review","TIME","Reviews estrogen-TME crosstalk in TC (PI3K/AKT/mTOR, RAS/Raf/MAPK).","review","review","Mechanistic estrogen-immune axis","Estrogen axis"),
 R("d","40315321","Targeting HMGB2 acts as dual immunomodulator by bolstering CD8+ T cell function and inhibiting tumor growth in hepatocellular carcinoma","10.1126/sciadv.ads8597",False,"Low",["IM","SC"],"HCC","scRNA+in vivo","scRNA","immunotherapy","HMGB2+ CD8+ T exhausted in HCC; tannic acid synergizes anti-PD-1.","in vivo/scRNA","off-topic (HCC)","-","-"),
 R("d","37279258","Papillary thyroid cancer immune phenotypes via tumor-infiltrating lymphocyte spatial analysis","10.1530/ERC-23-0110",True,"High",["IM","SP"],"PTC","TCGA WSI","AI TIL spatial","LNM/immune","3 immune phenotypes (desert 48%/excluded 34%/inflamed 18%); excluded=BRAF V600E+ higher LNM.","TCGA WSI","no functional","Therapeutic targeting of excluded phenotype","Target excluded IP"),
 R("d","33654093","RNA m6A methylation orchestrates cancer growth and metastasis via macrophage reprogramming","10.1038/s41467-021-21514-8",False,"Low",["IM","ME"],"pan-cancer","in vivo","METTL3","mets","Mettl3 loss in myeloid promotes TAM/IL-10, mets; attenuates anti-PD-1.","in vivo","off-topic (pan-cancer)","-","-"),
 R("d","38981044","Lactylated Apolipoprotein C-II Induces Immunotherapy Resistance by Promoting Extracellular Lipolysis","10.1002/advs.202406333",False,"Low",["IM","ME"],"NSCLC","multi-omics+in vivo","lactylome","immunotherapy","Lactyl-APOC2 drives Treg, ICI resistance in NSCLC.","in vivo","off-topic (NSCLC)","-","-"),
 R("d","41057823","Exosome-mediated metabolic reprogramming: effects on thyroid cancer progression and tumor microenvironment remodeling","10.1186/s12943-025-02470-z",True,"Medium",["IM","ME"],"TC","review","review","mets/TME","Exosomes drive TC metabolic reprogramming & immune escape.","review","review","Exosomal cargo causal tests","Exosome cargo"),
 R("d","39615165","Decoding tumor microenvironment: EMT modulation in breast cancer metastasis and therapeutic resistance","10.1016/j.biopha.2024.117714",False,"Low",["IM"],"breast","review","review","mets","TME-EMT in BC; CD73-TGF-beta dual blockade.","review","off-topic (breast)","-","-"),
 R("d","40207795","SERPINE1 Facilitates Metastasis in Gastric Cancer Through Anoikis Resistance and Tumor Microenvironment Remodeling","10.1002/smll.202500136",False,"Low",["IM"],"gastric","in vitro/in vivo","SERPINE1","mets","SERPINE1 drives GC mets & M2 TAM.","in vitro/in vivo","off-topic (gastric)","-","-"),
 R("d","39903533","5-HT orchestrates histone serotonylation and citrullination to drive neutrophil extracellular traps and liver metastasis","10.1172/JCI183544",True,"High",["IM","MO"],"MTC/NE","in vivo+FDA drug","NETs","MTC/NE liver mets via 5-HT->NETs; fluoxetine/SERT blocks.","in vivo+FDA drug","MTC subset of NE cancers","Confirm in primary MTC cohorts","MTC liver-mets trial","MTC NETs validation"),
 # ---- e: single-cell RNA-seq --------------------------------------------------
 R("e","39810624","Single-cell RNA-sequencing and spatial transcriptomic analysis reveal a distinct population of APOE- cells yielding pathological lymph node metastasis in papillary thyroid cancer","10.1002/ctm2.70172",True,"High",["SC","SP","MO","AL"],"PTC","scRNA+ST","scRNA+ST+ML","LNM","(see a/b) APOE- subpop drives LNM; 13-gene ML signature.","in vivo/in vitro+ST","single-center","Target APOE- therapeutically","APOE- targeted"),
 R("e","39540244","Spatial and Single-Cell Transcriptomics Unraveled Spatial Evolution of Papillary Thyroid Cancer","10.1002/advs.202404491",True,"High",["SC","SP","MO"],"PTC","scRNA+SRT","scRNA+SRT","evolution/mets","2 malignant/metastatic footprints; ferroptosis resistance aids PTC evolution.","SRT","single-center","Validate footprints across cohorts","Multi-center SRT"),
 R("e","37696831","Single-cell transcriptome analysis indicates fatty acid metabolism-mediated metastasis and immunosuppression in male breast cancer","10.1038/s41467-023-41318-2",False,"Low",["SC","ME"],"breast","scRNA","scRNA","mets","FASN FA metabolism drives BC mets & low immunity.","scRNA","off-topic (breast)","-","-"),
 R("e","40719066","Single-Cell RNA Sequencing Reveals the Heterogeneity in Differentiation Trajectory and Tumor Microenvironment Leading to More Aggressive Phenotypes of Papillary Thyroid Cancer in Children and Young Adult Patients","10.1002/advs.202417672",True,"High",["SC","IM"],"CAYA-PTC","scRNA (11 pts)","scRNA","aggressive/mets","CAYA-PTC lacks mild BRAF-like state->rapid invasive; emCAF_LAMP5 (FAP+) drives angiogenesis/mets; 68Ga-FAPI-PET.","scRNA","small n","Validate emCAF_LAMP5 across ages","CAYA emCAF validation"),
 R("e","39221971","Tryptophan 2,3-dioxygenase-positive matrix fibroblasts fuel breast cancer lung metastasis","10.1002/cac2.12608",False,"Low",["SC"],"breast","scRNA","scRNA","lung mets","(duplicate; breast)","in vivo/scRNA","off-topic","-","-"),
 R("e","36192735","CREB3L1 promotes tumor growth and metastasis of anaplastic thyroid carcinoma by remodeling the tumor microenvironment","10.1186/s12943-022-01658-x",True,"High",["SC","MO"],"ATC","scRNA+microarray","scRNA+in vivo","mets","CREB3L1 up in ATC; activates α-SMA+ CAFs via IL-1α; KPNA2 nuclear transport.","zebrafish/mouse+scRNA","no spatial","Spatial CAF-tumor interaction","Spatial ATC CAF"),
 R("e","41480746","An integrated single-cell and spatial transcriptomic atlas of thyroid cancer progression identifies prognostic fibroblast subpopulations","10.1172/jci.insight.191990",True,"High",["SC","SP"],"WDTC/ATC/pediatric","423,733 cells + ST","scRNA+ST","LNM/progression","POSTN+ myCAF associated with invasion, LNM, poor prognosis (42.3万 cells).","multi-institutional ST","rare subtypes small","Therapeutic targeting of myCAF","myCAF targeting"),
 R("e","37501099","ISG15 and ISGylation modulates cancer stem cell-like characteristics in promoting tumor growth of anaplastic thyroid carcinoma","10.1186/s13046-023-02751-9",True,"High",["SC","MO","ST"],"ATC","scRNA+in vivo","scRNA+in vivo","mets/stemness","ISG15 enriched in ATC CSCs; ISG15-ISGylation of KPNA2 stabilizes it->stemness; depletion inhibits mets.","mouse/zebrafish+scRNA","no spatial","ISG15/KPNA2 as ATC therapeutic","ATC CSC targeting"),
 R("e","41257484","Single-cell RNA sequencing reveals tumor cell and immune cell variations associated with lymphatic metastasis in papillary thyroid cancer","10.1530/EC-25-0514",True,"High",["SC","IM"],"PTC","scRNA (6 pts)","scRNA+CellChat","LNM","PTC with LM shows proliferation/migration pathways; CD8+ TRM pivotal via MHC-I/CD99/LCK.","6-pt scRNA","small n","Validate CD8+ TRM in larger LNM cohort","CD8 TRM validation"),
 R("e","38146045","Single-cell and bulk RNA sequencing reveal heterogeneity and diagnostic markers in papillary thyroid carcinoma lymph-node metastasis","10.1007/s40618-023-02262-6",True,"High",["SC","MO"],"PTC LNM","scRNA+bulk+66 pt","scRNA+bulk","LNM/dx","19-gene DEG model; S100A2 & DIO2 validated (RT-qPCR/IHC); DIO2 inhibits proliferation.","66-pt IHC/RT-qPCR","modest n","Multi-center DIO2 validation","DIO2 validation"),
 R("e","40201390","Comprehensive Analyses of Single-Cell and Bulk RNA Sequencing Data From M2 Macrophages to Elucidate the Immune Prognostic Signature in Patients with Gastric Cancer Peritoneal Metastasis","10.2147/ITT.S506143",False,"Low",["SC"],"gastric","scRNA+bulk","scRNA+WGCNA","PM prognosis","4-gene M2 macrophage signature in GC PM.","internal/external","off-topic (gastric)","-","-"),
 R("e","40315321","Targeting HMGB2 acts as dual immunomodulator ... in hepatocellular carcinoma","10.1126/sciadv.ads8597",False,"Low",["SC"],"HCC","scRNA","scRNA","immunotherapy","(duplicate; HCC)","in vivo/scRNA","off-topic","-","-"),
 R("e","40593465","The SOX12-YBX1-LDHA signaling axis drives metastasis in papillary thyroid carcinoma","10.1038/s41419-025-07797-5",True,"High",["SC","MO","ME"],"PTC","scRNA+bulk+CUT&Tag","scRNA+CUT&Tag","mets","SOX12->YBX1->LDHA promoter->TGF-beta->mets; LDHA rescue confirms.","clinical+functional","no spatial","Spatial SOX12/LDHA gradient","Spatial SOX12"),
 R("e","38990290","Artificial intelligence-based multi-modal multi-tasks analysis ... papillary thyroid carcinoma","10.1097/JS9.0000000000001875",True,"High",["SC","AL","MO"],"PTC","scRNA+DL","scRNA+DL","LNM/DFS","(see c) scRNA identified T-cell subsets; reduced B-cell diversity in BRAF LNM.","TCGA external","retrospective","Prospective DL","Prospective DL"),
 R("e","39829764","An integrated single-cell and spatial transcriptomic atlas of thyroid cancer progression identifies prognostic fibroblast subpopulations","10.1101/2025.01.08.631962",True,"High",["SC","SP"],"TC","scRNA+ST","scRNA+ST","invasion/LNM","myCAF only in malignant samples; abuts invasive tumor cells; preprint of 41480746.","ST","preprint/biorxiv","Reconciled with 41480746","-"),
 # ---- f: spatial transcriptomics / spatial multi-omics ------------------------
 R("f","41398964","Integrated spatial metabolomics and transcriptomics reveal the molecular landscape of papillary thyroid cancer and its lymph node metastasis","10.1186/s12967-025-07566-0",True,"High",["SP","ME","MO"],"PTC LNM","spatial metabolomics+ST","spatial multi-omics","LNM","Arginine-polyamine/glycolysis/lipid dysregulated; 5 metastasis-driving metabolites; NAT8L/SVCT-2 knockdown reduces mets.","TCGA+zf xenograft","single-center","Spatial multi-omics in ATC/MTC","Spatial multi-omics expand"),
 R("f","42373830","Multi-omics reveals tumor microenvironment heterogeneity and therapeutic vulnerabilities in peritoneal metastasis of gastric cancer","10.1038/s42003-026-10571-8",False,"Low",["SP"],"gastric","scRNA+ST","scRNA+ST","PM","TIGIT+CLDN18.2 dual block in GC PM.","in vivo","off-topic (gastric)","-","-"),
 R("f","41421038","Cellular and molecular determinants of lymph node metastasis in papillary thyroid carcinoma: Integrated multi-omics profiling and machine learning models","10.1016/j.compbiolchem.2025.108857",True,"High",["SC","SP","AL","MO"],"PTC LNM","scRNA+ST+bulk","multi-omics+ML","LNM","FN1-SDC4 axis validated by ST; 17-gene LNM signature; random forest LNM model.","in vitro+ST","single-center","Prospective FN1-SDC4 intervention","FN1-SDC4 trial"),
 R("f","41129052","Fibroblasts in the tumor microenvironment: heterogeneity and dynamic interactions in tumor progression revealed by spatial transcriptomics","10.1007/s13402-025-01108-y",False,"Low",["SP"],"pan-cancer","review","review","TME","POSTN+ myCAF predicts immune exclusion across cancers.","review","off-topic (pan-cancer)","-","-"),
 R("f","41608657","Breast cancer stem cell activity driven by ME18D gene expression in the tumor microenvironment","10.4252/wjsc.v18.i1.111348",False,"Low",["SP","ST"],"breast","scRNA+ST","scRNA+ST","prognosis","MED18 central in BCSC networks.","scRNA+ST","off-topic (breast)","-","-"),
 R("f","39923580","A comprehensive pan-cancer examination of transcription factor MAFF","10.1016/j.intimp.2025.114105",False,"Low",["SP"],"pan-cancer","multi-omics","multi-omics","prognosis","MAFF pan-cancer prognostic/immune.","multi-omics","off-topic (pan-cancer)","-","-"),
 R("f","39810624","Single-cell RNA-sequencing and spatial transcriptomic analysis ... papillary thyroid cancer","10.1002/ctm2.70172",True,"High",["SC","SP","MO","AL"],"PTC","scRNA+ST","scRNA+ST","LNM","(duplicate; see a/e) APOE- subpop.","in vivo/in vitro+ST","single-center","-","-"),
 R("f","39540244","Spatial and Single-Cell Transcriptomics Unraveled Spatial Evolution of Papillary Thyroid Cancer","10.1002/advs.202404491",True,"High",["SC","SP","MO"],"PTC","scRNA+SRT","scRNA+SRT","evolution","(duplicate; see e) footprints.","SRT","single-center","-","-"),
 R("f","41480746","An integrated single-cell and spatial transcriptomic atlas of thyroid cancer progression","10.1172/jci.insight.191990",True,"High",["SC","SP"],"TC","scRNA+ST","scRNA+ST","LNM","(duplicate; see e) POSTN+ myCAF.","multi-institutional ST","rare subtypes small","-","-"),
 R("f","39829764","An integrated single-cell and spatial transcriptomic atlas of thyroid cancer progression (preprint)","10.1101/2025.01.08.631962",True,"High",["SC","SP"],"TC","scRNA+ST","scRNA+ST","invasion","(duplicate; see e) myCAF.","ST","preprint","-","-"),
 R("f","40456735","Neuro-immune crosstalk in cancer: mechanisms and therapeutic implications","10.1038/s41392-025-02241-8",False,"Low",["IM"],"pan-cancer","review","review","TIME","(duplicate; pan-cancer)","review","off-topic","-","-"),
 # ---- g: prognosis / recurrence / distant metastasis -------------------------
 R("g","31792675","A novel RNA sequencing-based risk score model to predict papillary thyroid carcinoma recurrence","10.1007/s10585-019-10011-4",True,"High",["PR","MO"],"PTC","TCGA","Cox+LASSO","recurrence","5-gene risk score (TOP2A, RP11-180M15.7, RP11-635N19.1, PROSER3, TMEM139); HR 6.62 train/3.40 val.","chronologic split val","TCGA only","External validation","External recurrence model"),
 R("g","41877795","Development and validation of a machine learning model for predicting high-risk distant metastatic recurrence in differentiated thyroid cancer","10.3389/fmed.2026.1790226",True,"High",["AL","PR"],"DTC","1245 pts","LASSO+ML (XGBoost)","distant metastatic recurrence","XGBoost AUC 0.88 (374-case external); 8 predictors incl BRAF V600E, sTg.","external val (374)","retrospective","Prospective external validation","Prospective DTC-DM"),
 R("g","37851243","BRAF V600E mutation in papillary thyroid microcarcinoma: is it a predictor for the prognosis ...?","10.12020-023-03564-8",True,"Medium",["MO","PR"],"PTMC","322 pts","PSM+logistic","recurrence","BRAFV600E not associated with outcomes after RAI in intermediate/high-risk PTMC.","PSM","single center","Larger PTMC cohort","PTMC outcomes"),
 R("g","32615728","Development and Validation of a Risk Scoring System Derived from Meta-Analyses of Papillary Thyroid Cancer","10.3803/EnM.2020.35.2.435",True,"Medium",["PR"],"PTC","5 meta-analyses","RSS","prognosis","RSS1 (8 vars) superior to AJCC/ATA for PTC risk.","meta-derived","no individual data","Individual-level validation","Individual-level RSS"),
 R("g","29405275","Surgeon volume and prognosis of patients with advanced papillary thyroid cancer and lateral nodal metastasis","10.1002/bjs.10655",True,"Low",["PR"],"PTC N1b","1103 pts","Cox","recurrence","High surgeon volume->lower structural recurrence (HR 1.46 low-vol); not distant/death.","Cox","observational","Causal volume mechanisms","Volume quality"),
 R("g","37934030","A novel cuproptosis-related lncRNA prognostic signature in thyroid cancer","10.2217/bmm-2023-0216",True,"Medium",["PR"],"TC","TCGA","Cox","prognosis/recurrence","4 cuproptosis-lncRNA signature; AUC 0.830/0.790/0.824 at 1/3/5y.","TCGA","no wet-lab","Cuproptosis mechanism in TC","Cuproptosis validation"),
 R("g","38311812","Pregnancy and the disease recurrence of patients previously treated for differentiated thyroid cancer","10.1097/CM9.0000000000003008",True,"Low",["PR"],"DTC","10 studies (meta)","meta","recurrence","Pregnancy minimal association with DTC recurrence (OR 0.75).","meta (10)","heterogeneity","Prospective pregnancy cohort","Pregnancy-DTC"),
 R("g","41084771","Aggressiveness of papillary thyroid carcinoma: a comprehensive analysis from molecular mechanisms to clinical applications","10.5603/fhc.108530",True,"Medium",["MO","PR"],"PTC","review","review","aggressiveness","Integrates molecular, epigenetic, immune & imaging for PTC aggressiveness.","review","review","Subtype-specific aggressiveness","Subtype aggressiveness"),
 R("g","31412224","PROGNOSIS OF DIFFERENTIATED THYROID CARCINOMA IN PATIENTS WITH GRAVES DISEASE","10.4158/EP-2019-0201",True,"Low",["PR"],"DTC+Graves","25 studies (meta)","meta","distant mets","GD-DTC higher multifocality & distant mets at dx; not mortality/recurrence.","meta (25)","observational","Individual-level GD cohort","GD-DTC cohort"),
 R("g","27697309","Recurrence factors and prevention of complications of pediatric differentiated thyroid cancer","10.1016/j.asjsur.2016.09.001",True,"Low",["PR"],"pediatric DTC","43 pts","Cox","recurrence","LNM, ETE, lesion number are recurrence risk factors in children.","Cox","small n","Larger pediatric cohort","Pediatric DTC"),
 R("g","36704213","Breast-Conserving Surgery in Triple-Negative Breast Cancer","10.1155/2023/5431563",False,"Low",["PR"],"breast","retrospective","Cox","recurrence","TNBC BCS+NAC outcomes.","retrospective","off-topic (breast)","-","-"),
 R("g","37132252","Investigating the impact of tumor location and size on the risk of recurrence for papillary thyroid carcinoma in the isthmus","10.1002/cam4.6023",True,"Low",["PR"],"iPTC","116 pts","Cox","recurrence","IPF<=5.57 independent prognostic for isthmic PTC RFS.","Cox","single center","External isthmic validation","Isthmic PTC"),
 R("g","41817109","Selective Use of Radioiodine Therapy in Differentiated Thyroid Carcinoma","10.1177/10507256261416869",True,"Medium",["PR"],"DTC","3330 pts","Cox+IPTW","DSS/DFS","RAI not associated with overall DSS; >80% risk reduction in metastatic DTC.","population cohort","retrospective","Prospective RAI allocation","RAI trial"),
 R("g","32668875","Predictive analysis of distant metastasis after primary treatment of papillary thyroid cancer in patients under 18 years old","10.3760/cma.j.cn115330-00025",True,"Low",["PR"],"pediatric PTC","180 pts","Cox","distant mets","Age<=15 & bilateral tumor independent DM risk in children.","Cox","single center","Multi-center pediatric DM","Pediatric DM"),
 R("g","41419184","Prognostic Value of BRAF V600E Mutation in Papillary Thyroid Carcinoma: A Meta-Analysis","10.1016/j.eprac.2025.12.003",True,"High",["MO","PR"],"PTC","46 studies/20,570 pts","meta","nodal/recurrence/death","BRAF V600E OR 1.38 nodal, 1.56 recurrence; NOT distant (0.75) or death (0.97).","meta (46)","heterogeneity","Subtype-stratified meta","Subtype meta"),
 # ---- h: metastatic stemness subpopulation ------------------------------------
 R("h","25426258","Stem cell biology in thyroid cancer: Insights for novel therapies","10.4252/wjsc.v6.i5.614",True,"Low",["ST","MO"],"TC","review","review","stemness","Reviews CSC identification (ALDH, CD133, side-population) in TC.","review","review","CSC-targeted therapy trials","CSC targeting"),
 R("h","33186350","Nucleotide de novo synthesis increases breast cancer stemness and metastasis via cGMP-PKG-MAPK","10.1371/journal.pbio.3000872",False,"Low",["ST","ME"],"breast","in vitro/in vivo","metabolome","stemness/mets","PRPS2/nucleotide synthesis->stemness in BC.","in vitro/in vivo","off-topic (breast)","-","-"),
 R("h","39595993","DLK1 Is Associated with Stemness Phenotype in Medullary Thyroid Carcinoma Cell Lines","10.3390/ijms252211924",True,"Medium",["ST","MO"],"MTC","cell lines","in vitro","stemness","DLK1+ cells higher stemness/spheroid/dye-efflux in MTC.","in vitro","cell-line only","In vivo/primary MTC validation","MTC DLK1 validation"),
 R("h","39810624","Single-cell RNA-sequencing and spatial transcriptomic analysis ... papillary thyroid cancer","10.1002/ctm2.70172",True,"High",["SC","SP","MO","AL","ST"],"PTC","scRNA+ST","scRNA+ST","LNM/stemness","(duplicate; see a/b/e/f) APOE- dediff tip = stem-like metastatic.","in vivo/in vitro+ST","single-center","-","-"),
 R("h","37501099","ISG15 and ISGylation modulates cancer stem cell-like characteristics ... anaplastic thyroid carcinoma","10.1186/s13046-023-02751-9",True,"High",["SC","MO","ST"],"ATC","scRNA+in vivo","scRNA+in vivo","stemness/mets","(duplicate; see e) ISG15/KPNA2 CSC in ATC.","mouse/zebrafish+scRNA","no spatial","-","-"),
 R("h","41480746","An integrated single-cell and spatial transcriptomic atlas ... thyroid cancer progression","10.1172/jci.insight.191990",True,"High",["SC","SP"],"TC","scRNA+ST","scRNA+ST","LNM","(duplicate; see e) myCAF niche.","multi-institutional ST","rare subtypes small","-","-"),
 R("h","36192735","CREB3L1 promotes tumor growth and metastasis of anaplastic thyroid carcinoma ...","10.1186/s12943-022-01658-x",True,"High",["SC","MO"],"ATC","scRNA+in vivo","scRNA+in vivo","mets","(duplicate; see e) CAF remodeling.","zebrafish/mouse+scRNA","no spatial","-","-"),
 R("h","40593465","The SOX12-YBX1-LDHA signaling axis drives metastasis in papillary thyroid carcinoma","10.1038/s41419-025-07797-5",True,"High",["SC","MO","ME"],"PTC","scRNA+bulk","scRNA","mets","(duplicate; see e) metabolic-stemness axis.","clinical+functional","no spatial","-","-"),
 R("h","42327722","MGST1 drives lymph node metastasis in papillary thyroid carcinoma via mitochondrial metabolic reprogramming and immune suppression","10.3389/fimmu.2026.1848083",True,"High",["ME","IM","MO","ST"],"PTC","TCGA/GTEx+cohort+scRNA","multi-omics+ML+pharm","LNM","Mito-high/immune-cold subtype; MGST1 core predictor AUC 0.833; MGST1 at dediff tip = stem-like metastatic; toxoflavin inhibits.","external val+in vitro","single-center SC","MGST1 targeted therapy trial","MGST1 targeted"),
 R("h","40855521","NSUN2-tRNAVal-CAC-axis ... triple-negative breast cancer","10.1186/s11658-025-00781-z",False,"Low",["ME"],"TNBC","in vitro/in vivo","tRNA m5C","glycolysis","(duplicate; TNBC)","in vitro/in vivo","off-topic","-","-"),
 R("h","38935111","The association between immune cells and breast cancer","10.1097/JS9.0000000000001840",False,"Low",["IM"],"breast","MR+meta","immune","prognosis","(duplicate; breast)","MR+meta","off-topic","-","-"),
 R("h","37696831","Single-cell transcriptome analysis ... male breast cancer","10.1038/s41467-023-41318-2",False,"Low",["SC","ME"],"breast","scRNA","scRNA","mets","(duplicate; breast)","scRNA","off-topic","-","-"),
 R("h","39221971","Tryptophan 2,3-dioxygenase-positive matrix fibroblasts ... breast cancer","10.1002/cac2.12608",False,"Low",["IM","SC"],"breast","scRNA+in vivo","scRNA","lung mets","(duplicate; breast)","in vivo/scRNA","off-topic","-","-"),
 R("h","41608657","Breast cancer stem cell activity driven by ME18D ...","10.4252/wjsc.v18.i1.111348",False,"Low",["SP","ST"],"breast","scRNA+ST","scRNA+ST","prognosis","(duplicate; breast)","scRNA+ST","off-topic","-","-"),
 R("h","39923580","A comprehensive pan-cancer examination of transcription factor MAFF","10.1016/j.intimp.2025.114105",False,"Low",["SP"],"pan-cancer","multi-omics","multi-omics","prognosis","(duplicate; pan-cancer)","multi-omics","off-topic","-","-"),
 R("h","40315321","Targeting HMGB2 ... hepatocellular carcinoma","10.1126/sciadv.ads8597",False,"Low",["IM","SC"],"HCC","scRNA+in vivo","scRNA","immunotherapy","(duplicate; HCC)","in vivo/scRNA","off-topic","-","-"),
 # ---- i: metabolic reprogramming metastasis ----------------------------------
 R("i","41057823","Exosome-mediated metabolic reprogramming: effects on thyroid cancer progression and tumor microenvironment remodeling","10.1186/s12943-025-02470-z",True,"Medium",["IM","ME"],"TC","review","review","mets/TME","(duplicate; see d) exosomes drive TC metabolic reprogramming.","review","review","-","-"),
 R("i","39747873","The protein circPETH-147aa regulates metabolic reprogramming in hepatocellular carcinoma","10.1038/s41467-024-55577-0",False,"Low",["ME"],"HCC","in vitro/in vivo","circRNA","glycolysis","circPETH-147aa drives HCC glycolysis.","in vitro/in vivo","off-topic (HCC)","-","-"),
 R("i","38953696","ACSL3 regulates breast cancer progression via lipid metabolism reprogramming and the YES1/YAP axis","10.20892/j.issn.2095-3941.2023.0309",False,"Low",["ME"],"breast","in vitro/in vivo","ACSL3","mets","ACSL3 suppresses BC via lipid metabolism.","in vitro/in vivo","off-topic (breast)","-","-"),
 R("i","40470773","METTL14-Mediated M6A Modification of LINC01094 Induces Glucose Metabolic Reprogramming in Breast Cancer","10.1002/advs.202410386",False,"Low",["ME"],"breast","in vitro/in vivo","m6A","glycolysis","LINC01094 m6A->glycolysis in BC.","in vitro/in vivo","off-topic (breast)","-","-"),
 R("i","39192979","The role of metabolic reprogramming in immune escape of triple-negative breast cancer","10.3389/fimmu.2024.1424237",False,"Low",["ME","IM"],"TNBC","review","review","immune escape","Metabolic immune escape in TNBC.","review","off-topic (TNBC)","-","-"),
 R("i","38272883","SHMT2 promotes papillary thyroid cancer metastasis through epigenetic activation of AKT signaling","10.1038/s41419-024-06476-1",True,"High",["ME","MO"],"PTC","specimens+in vivo","proteomic+functional","mets","SHMT2 generates SAM->methylates PTEN->AKT->PTC mets; AKT block abolishes.","in vitro/in vivo","no SC","Spatial SHMT2/PTEN gradient","Spatial SHMT2"),
 R("i","41398964","Integrated spatial metabolomics and transcriptomics reveal the molecular landscape of papillary thyroid cancer and its lymph node metastasis","10.1186/s12967-025-07566-0",True,"High",["SP","ME","MO"],"PTC LNM","spatial metabolomics+ST","spatial multi-omics","LNM","(duplicate; see f) metabolites NAT8L/SVCT-2.","TCGA+zf","single-center","-","-"),
 R("i","42327722","MGST1 drives lymph node metastasis in papillary thyroid carcinoma via mitochondrial metabolic reprogramming and immune suppression","10.3389/fimmu.2026.1848083",True,"High",["ME","IM","MO","ST"],"PTC","TCGA/GTEx+cohort+scRNA","multi-omics+ML+pharm","LNM","(duplicate; see h) Mito-high/immune-cold; MGST1 AUC 0.833.","external val+in vitro","single-center SC","-","-"),
 R("i","41219790","A novel protein cPFKFB4 encoded by hsa_circ_0065394 strengthens PKM2-mediated glucose metabolic reprogramming ... pancreatic cancer","10.1186/s12943-025-02500-w",False,"Low",["ME"],"pancreatic","in vitro/in vivo","circRNA","glycolysis","cPFKFB4->PKM2 glycolysis in PC.","in vitro/in vivo","off-topic (PC)","-","-"),
 R("i","40855521","NSUN2-tRNAVal-CAC-axis ... triple-negative breast cancer","10.1186/s11658-025-00781-z",False,"Low",["ME"],"TNBC","in vitro/in vivo","tRNA m5C","glycolysis","(duplicate; TNBC)","in vitro/in vivo","off-topic","-","-"),
 R("i","40353071","Reprogramming of fatty acid metabolism in thyroid cancer: Potential targets and mechanisms","10.21147/j.issn.1000-9604.2025.02.09",True,"Medium",["ME"],"TC","review","review","mets","Reviews FA metabolic reprogramming targets in TC.","review","review","FA-targeted therapy trials","FA-targeted"),
 R("i","40980146","Thyroid cancer: From molecular insights to therapy (Review)","10.3892/ol.2025.15266",True,"Medium",["MO","ME","PR"],"PTC/FTC/MTC/ATC","review","review","therapy","Subtype molecular (BRAF/RAS/RET/TERT/p53) & metabolic overview.","review","review","Subtype-specific metabolic trials","Subtype trials"),
 R("i","42280115","PKM2-Mediated Glycolytic Reprogramming in Thyroid Cancer: Mechanistic Insights and Therapeutic Potential","10.3390/molecules31111811",True,"Medium",["ME","MO"],"TC","review","review","glycolysis","Reviews PKM2 glycolytic reprogramming in TC.","review","review","PKM2 inhibitor trials in TC","PKM2 trials"),
 R("i","37031273","LncRNA GLTC targets LDHA for succinylation and enzymatic activity to promote progression and radioiodine resistance in papillary thyroid cancer","10.1038/s41418-023-01157-6",True,"High",["ME","MO"],"PTC","specimens+in vivo","mass-spec+functional","distant mets/RAI","GLTC binds LDHA, blocks SIRT5->K155 succinylation->glycolysis & distant mets; reversal RAI resistance.","in vitro/in vivo","no SC","Spatial GLTC/LDHA gradient","Spatial GLTC"),
 R("i","40850678","Research progress and therapeutic strategies in hepatocellular carcinoma metabolic reprogramming","10.1016/j.jare.2025.08.023",False,"Low",["ME"],"HCC","review","review","mets","HCC metabolic reprogramming.","review","off-topic (HCC)","-","-"),
]

# ---- Build records -----------------------------------------------------------
records = []
seen = {}
for r in ROWS:
    (q, pmid, title, doi, thy, rel, dims, dis, ds, meth, ep, mf, val, lim, gap, fut) = r
    if pmid in seen:
        seen[pmid]["queries"].append(q)
        # merge dimensions (union)
        for d in dims:
            if d not in seen[pmid]["dimensions"]:
                seen[pmid]["dimensions"].append(d)
        continue
    rec = {
        "pmid": pmid, "title": title, "doi": doi,
        "in_scope_thyroid": thy, "relevance": rel,
        "dimensions": dims,
        "queries": [q], "disease": dis, "data_source": ds,
        "method": meth, "endpoint": ep, "main_finding": mf,
        "validation": val, "limitation": lim, "gap": gap,
        "future_direction": fut,
    }
    seen[pmid] = rec
    records.append(rec)

# dimension label map
LAB = {"MO":"分子机制","IM":"免疫微环境","SC":"单细胞","SP":"空间组学","AL":"算法方法","PR":"预后转移","ME":"代谢重编程","ST":"转移干性"}
for rec in records:
    rec["dimension_labels"] = [LAB[d] for d in rec["dimensions"]]

# ---- Summary ----------------------------------------------------------------
in_scope = [r for r in records if r["in_scope_thyroid"]]
excluded = [r for r in records if not r["in_scope_thyroid"]]
rel_counts = {"High":0,"Medium":0,"Low":0}
for r in in_scope:
    rel_counts[r["relevance"]] += 1
dim_tally = {}
for r in in_scope:
    for d in r["dimensions"]:
        dim_tally[d] = dim_tally.get(d,0)+1
dim_tally_labels = {LAB[k]:v for k,v in sorted(dim_tally.items())}

# run#11 baseline for delta
baseline_records = json.load(open(OUT))["records"]
baseline = set(x["pmid"] for x in baseline_records)
all_pmids = set(r["pmid"] for r in records)
new_vs_baseline = sorted(all_pmids - baseline, key=lambda x:int(x))
dropped = sorted(baseline - all_pmids, key=lambda x:int(x))

summary = {
    "raw_rows": len(ROWS),
    "unique_pmids": len(all_pmids),
    "in_scope_thyroid": len(in_scope),
    "excluded_nonthyroid_or_duplicate": len(excluded),
    "relevance_counts": rel_counts,
    "dimension_tallies_multitag": dim_tally_labels,
    "new_vs_run11_baseline": new_vs_baseline,
    "dropped_from_run11_baseline_relevance_cutoff": dropped,
    "new_publications_reliable": len(new_vs_baseline),
    "plateau_note": "All retrieved PMIDs this run were already present in the run#11 104-corpus; 0 genuinely new thyroid papers. 5 baseline PMIDs (38981044, 39615165, 40207795, 39903533, 40855521) fell off the 15-row relevance cutoff of the 9 queries and are NOT new literature.",
}

out = {
    "search_date": RUN_DATE,
    "run": "run#12",
    "source": "mcp__paper-search-mcp__search_pubmed (DeferExecuteTool); max_results=15; sort=relevance",
    "queries": QUERIES,
    "summary": summary,
    "corpus_note": "Re-anchored from 9 live complementary queries executed 2026-08-03. Dedup by PMID; in-scope thyroid papers retained; off-topic (breast/gastric/HCC/pancreatic/TNBC/pan-cancer/colorectal) and duplicates excluded. Multi-tag dimensions per record.",
    "records": records,
}

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)

print("Wrote", OUT)
print("raw_rows:", summary["raw_rows"], "unique:", summary["unique_pmids"],
      "in_scope:", summary["in_scope_thyroid"], "excluded:", summary["excluded_nonthyroid_or_duplicate"])
print("relevance:", rel_counts)
print("dimension_tallies:", dim_tally_labels)
print("new_vs_run11:", new_vs_baseline, "(count", len(new_vs_baseline), ")")
print("dropped_from_baseline:", dropped)
