# -*- coding: utf-8 -*-
"""Run #6 corpus builder.
Merges run#5 baseline (search_results_latest.json, 106 records) with the 32
new in-scope thyroid papers surfaced by the run#6 pub_date recency sweep,
plus newly surfaced off-topic (excluded) papers, and writes a cumulative
search_results_latest.json with corpus_delta_vs_run5.
"""
import json, datetime

BASE = "search_results_latest.json"
with open(BASE, "r", encoding="utf-8") as f:
    base = json.load(f)

base_records = base["records"]
base_pmids = { (r.get("paper_id") or r.get("pmid")) for r in base_records }
base_inscope = { (r.get("paper_id") or r.get("pmid")) for r in base_records if r.get("in_scope") }

# ---- 32 NEW in-scope thyroid papers (full records from run#6 MCP retrieval) ----
new_inscope = [
 {"paper_id":"35388548","title":"Analysis of anti-apoptotic PVT1 oncogene and apoptosis-related proteins (p53, Bcl2, PD-1, and PD-L1) expression in thyroid carcinoma.","authors":"Ibrahiem AT; Makhdoom AK; Alanazi KS; Alanazi AM; Mukhlef AM; Elshafey SH; Toraih EA; Fawzy MS","abstract":"An aberrant expression of long non-coding RNA PVT1 has been associated with apoptosis in various cancer types. We aimed to explore the PVT1 and four apoptosis-related proteins (p53, Bcl2, and PD-1/PD-L1) signature in thyroid cancer (TC). The PVT1 expression level was measured in 64 FFPE TC paired samples by real-time quantitative PCR. Overall and stratified analyses by different clinicopathological features were done. The apoptotic proteins were evaluated by immunohistochemistry staining. Overall analysis showed significant PVT1 upregulation in TC tissues (p<0.001). Similarly, subgroup analysis by BRAFV600E mutation showed consistent results. Lower expression of p53 was associated with mortality (p=0.001). Bcl2 overexpression was associated with greater tumor size (p=0.005). PD-1 expression was associated with lymph node metastasis (p=0.004). Enhanced PD-L1 expression in the tumor was associated with a higher tumor stage, lymphovascular invasion, and mortality risk. Kaplan-Meier curves for overall survival showed that low p53 and high PD-L1 expressions were associated with lower survival time. The p53-positive staining is associated with a 90% decreased mortality risk (HR=0.10, 95%CI=0.02-0.47, p=0.001), while patients with high PD-L1 were five times more likely to die (HR=4.74, 95%CI=1.2-18.7, p=0.027). Our results confirm the upregulation of PVT1 in TC. The apoptosis-related proteins (p53, Bcl2, and PD-1/PD-L1) showed different prognostic utility in TC patients.","doi":"10.1002/jcla.24390","published_date":"2022-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/35388548/","source_queries":["a"],"in_scope":True,"relevance":"Medium","dimensions":["molecular","immune"]},
 {"paper_id":"38233939","title":"TIPARP as a prognostic biomarker and potential immunotherapeutic target in male papillary thyroid carcinoma.","authors":"Zhang J; Zhou X; Yao F; Zhang J; Li Q","abstract":"Male patients with papillary thyroid carcinoma (PTC) tend to have poorer prognosis compared to females, partially attributable to a higher rate of lymph node metastasis (LNM). Developing a precise predictive model for LNM occurrence in male PTC patients is imperative. We conducted a comprehensive search of publicly available microarray datasets to identify candidate genes continuously upregulated or downregulated during PTC progression in male patients only. Univariate Cox analysis and lasso regression were utilized to construct an 11-gene signature predictive of LNM. TIPARP emerged as a key candidate gene, which we validated at the protein level using immunohistochemical staining. A prognostic nomogram incorporating the signature and clinical factors was developed based on the TCGA cohort. The 11-gene signature demonstrated good discriminative performance for LNM prediction in training and validation datasets. High TIPARP expression associated with advanced stage, high T stage, and presence of LNM. A prognostic nomogram integrating the signature and clinical variables reliably stratified male PTC patients into high and low recurrence risk groups. We identified a robust 11-gene signature and prognostic nomogram for predicting LNM occurrence in male PTC patients. We propose TIPARP as a potential contributor to inferior outcomes in males, warranting further exploration as a prognostic biomarker and immunotherapeutic target.","doi":"10.1186/s12935-024-03223-6","published_date":"2024-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/38233939/","source_queries":["a"],"in_scope":True,"relevance":"Medium","dimensions":["immune","prognosis","molecular"]},
 {"paper_id":"39749465","title":"A Comparison of the Predictive Value of International Medullary Thyroid Carcinoma Grading System (IMTCGS) With That of Other Risk Factors in a Chinese Medullary Thyroid Carcinoma Cohort.","authors":"Ni J; Zhang X; Liu Y; Ling Y","abstract":"The International Medullary Thyroid Carcinoma Grading System (IMTCGS) was recently introduced in medullary thyroid carcinoma (MTC). This study aimed to assess the predictive value of the IMTCGS for disease response and survival, and compare its predictive ability with that of other traditional risk factors in a Chinese MTC cohort. The data of 137 MTC patients undergoing initial surgery between January 2004 and June 2023 were included. IMTCGS, TNM stage, postoperative calcitonin, postoperative CEA, and vascular invasion were associated with PFS. Postoperative calcitonin was the only independent predictor for PFS in multivariate analysis (HR=1.002, p=0.002). IMTCGS was the only independent predictor for DSS (HR=11.23, p=0.05). The AUC of IMTCGS was 0.81 for disease-specific death. In this Chinese MTC cohort, IMTCGS was a powerful predictor of disease-specific death, while postoperative calcitonin was a powerful predictor of structural recurrence.","doi":"10.1111/cen.15195","published_date":"2025-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/39749465/","source_queries":["g"],"in_scope":True,"relevance":"Medium","dimensions":["prognosis"]},
 {"paper_id":"40001321","title":"Comprehensive transcriptomic profiling reveals molecular characteristics and biomarkers associated with risk stratification in papillary thyroid carcinoma.","authors":"Yan C; Zheng C; Luo J; Wu X; Meng X; Lv C; Shen S; Zhou M; Wang O","abstract":"Papillary thyroid carcinoma (PTC) is one of the most common endocrine malignancies, with varying levels of risk and clinical behavior. A better understanding of the molecular characteristics could improve molecular diagnosis and risk assessment. We performed whole transcriptomic sequencing on 113 PTC cases, including 70 high-risk and 43 low-risk Chinese patients. Low-risk PTCs showed significant upregulation of immune-related genes and increased immune cell infiltration, whereas high-risk PTCs presented extensive alterations in gene expression and activation of oncogenic signaling pathways. We developed a 31-gene transcriptomic signature (PTCrisk) for differentiating high-risk from low-risk PTCs, validated across both in-house and external multicenter cohorts. PTCrisk scores were positively correlated with tumor size, lymph node metastasis, TNM stage, and BRAF mutation status.","doi":"10.1002/2056-4538.70022","published_date":"2025-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/40001321/","source_queries":["a"],"in_scope":True,"relevance":"Medium","dimensions":["molecular","prognosis"]},
 {"paper_id":"40025314","title":"UBC9: a novel therapeutic target in papillary thyroid carcinoma.","authors":"Zhang H; Wu J; Hu H; Tang H; Tan K; Hu M; Zhu G","abstract":"Papillary thyroid carcinoma (PTC) is the most common type of thyroid cancer. Despite the favorable prognosis in some patients, there remains a risk of lymph node metastasis and death. We performed differential expression analysis using TCGA data, and prognostic analysis of differential genes. UBC9 expression level was significantly elevated in PTC tumor tissues, and in vitro experiments demonstrated that UBC9 knockdown inhibited tumor proliferation and migration and promoted apoptosis. UBC9 is closely linked to immunity in PTC, and UBC9 may be a potential therapeutic target.","doi":"10.1007/s40618-024-02523-y","published_date":"2025-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/40025314/","source_queries":["a"],"in_scope":True,"relevance":"Low","dimensions":["molecular","immune"]},
 {"paper_id":"41078274","title":"A Comparison of Different Radiomics Methods Predicting Cervical Lymph Node Metastasis in Papillary Thyroid Carcinoma.","authors":"Deng Y; Zheng L; Zhang M; Xu L; Li Q; Zhou L; Wang Q; Gong Y; Li S","abstract":"The preoperative identification of cervical lymph node metastasis in PTC is essential in tailoring surgical treatment. We developed an ultrasound-based handcrafted radiomics model, a deep learning radiomics model, and a combined model. 441 patients (308 training, 133 testing). In the training set, the AUC of the combined model (0.790) was significantly higher than handcrafted (0.743) and deep learning radiomics (0.730). In the testing set, combined model AUC 0.761. The handcrafted radiomics model exhibited high accuracy in both sets. The combined model based on conventional ultrasound images enhances predictive performance compared to radiomics models alone.","doi":"10.1002/jcu.70102","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41078274/","source_queries":["c"],"in_scope":True,"relevance":"Medium","dimensions":["algorithm"]},
 {"paper_id":"41664099","title":"Prediction of malignancy and metastasis of thyroid cancer by combined feature sets through advanced machine learning.","authors":"Xie R; Xiao G; Ding M; Xu D; Tan D; Zhao Y; Zheng S; Zou Z; Du D; Shen D; Gu J; Fei J","abstract":"803 patients examined using ultrasound for thyroid nodules (369 benign, 433 malignant, 118 LNM). Transfer learning extracted features of ultrasound 2D images. Incorporated imaging and tabular clinical features to predict malignancy and LNM. Several ML models (random forest, XGB, Naive Bayes, MLP). AUROC 0.82 for TC diagnosis and 0.78 for LNM prediction. Synergistic performance when clinical characteristics and ultrasonographic images combined. TI-RADS correlated with malignancy and LNM.","doi":"10.1186/s12911-026-03372-w","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41664099/","source_queries":["c"],"in_scope":True,"relevance":"Medium","dimensions":["algorithm"]},
 {"paper_id":"41686681","title":"Dual-channel ultrasonic images empowered deep learning: significantly improving prediction of occult central lymph node metastases in solitary papillary thyroid microcarcinoma.","authors":"Li M; Jia C; Li G; Shi Q; Liu L","abstract":"Central lymph node metastasis (CLNM) elevates postoperative recurrence risk in PTMC. 461 PTMC patients from two hospitals. Dual-channel DL model combining longitudinal and transverse ultrasound images. Combined model integrating DL features and clinical indicators achieved AUC 0.900 training / 0.873 external test, surpassing single-direction DL and clinical models. Offers a non-invasive method for predicting occult CLNM.","doi":"10.2478/raon-2026-0006","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41686681/","source_queries":["c"],"in_scope":True,"relevance":"Medium","dimensions":["algorithm"]},
 {"paper_id":"41879411","title":"Inhibitory effect of vemurafenib combined with panobinostat on human anaplastic thyroid cancer cells.","authors":"Li Y; Gao H; Zhang P; Wang W; Zhou J; Cui J; Xue D; Zhang B; Li P; Fan L; Xu J","abstract":"Anaplastic thyroid cancer (ATC) has poor prognosis. This study investigated vemurafenib (Ve) combined with panobinostat (Pa) on ATC cells (FRO, ARO). CompuSyn verified synergistic effect. Ve+Pa suppressed proliferation, migration, invasion, glucose consumption, enhanced apoptosis. NIS and iodine metabolism molecules upregulated, GLUT1 downregulated. Ve+Pa exerts synergistic inhibitory effect on growth and metastasis of ATC cells while promoting redifferentiation.","doi":"10.36721/PJPS.2026.39.5.REG.13646.1","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41879411/","source_queries":["b"],"in_scope":True,"relevance":"Medium","dimensions":["molecular","metabolic"]},
 {"paper_id":"41931576","title":"Utilizing the transformer mechanism to predict cervical lymph node metastasis in patients with papillary thyroid carcinoma.","authors":"Chen H; Ruan F; Zhu L; Zhuang Y; Ye X; Liu X; Zeng J","abstract":"540 PTC patients from two hospitals. Vision transformer (ViT) model built from 2D ultrasound images, compared with CNN, Clinical-Rad, and clinical models. ViT AUC 0.807 internal / 0.809 external, significantly exceeding clinical model (0.595-0.669). ViT showed stable superior performance vs CNN and radiomics combined model in validation cohorts, enhancing diagnostic capability of radiologists.","doi":"10.1371/journal.pone.0345937","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41931576/","source_queries":["c"],"in_scope":True,"relevance":"Medium","dimensions":["algorithm"]},
 {"paper_id":"41964784","title":"Lipocalin 2 promotes papillary thyroid cancer progression through activation of glycolysis via Hippo/YAP1/HIF1alpha axis.","authors":"Qian X; Tang J; Jiang L; Li L; Shen C; Teng L","abstract":"LCN2 was significantly upregulated in PTC and correlated with extrathyroidal extension and lymph node metastasis. LCN2 knockdown inhibited PTC proliferation, migration, invasion, and glycolysis; overexpression opposite; reversed by 2-DG. LCN2 directly targeted YAP1, modulating HIF1alpha transcriptional activity to enhance glycolysis. LCN2 promotes glycolysis, proliferation, invasion, migration by activating Hippo/YAP1/HIF1alpha axis.","doi":"10.1007/s40618-026-02887-3","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41964784/","source_queries":["b"],"in_scope":True,"relevance":"High","dimensions":["molecular","metabolic"]},
 {"paper_id":"41997788","title":"Diagnostic Accuracy of Ultrasound Radiomics for Cervical Lymph-Node Metastasis in Papillary Thyroid Carcinoma: Evidence Predominantly From Chinese Cohorts.","authors":"Nabavizadeh SS; Safari F; Mehrian SRA; Ghanaatpisheh A; Abbaspour A; Alinazari MMK; Setayesh M; Nabavizadeh A","abstract":"Systematic review/meta-analysis (PROSPERO) of 60 studies (10,852 patients; 4,716 LNM). Radiomics-only pooled sensitivity 0.72, specificity 0.81, AUC 0.83. Adding clinical variables raised sensitivity to 0.79 and AUC to 0.88 (not significant, p=0.33). ML pipelines outperformed deep learning (AUC 0.86 vs 0.79); highest for lateral nodes (AUC 0.94). External-validation cohorts lower (AUC 0.79). Ultrasound radiomics provides good non-invasive accuracy for cervical nodal staging in PTC, especially lateral compartments; advantage over clinical variables modest.","doi":"10.1016/j.ultrasmedbio.2026.01.017","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41997788/","source_queries":["c"],"in_scope":True,"relevance":"High","dimensions":["algorithm"]},
 {"paper_id":"42002564","title":"The mechanism of fibronectin 1 promoting papillary thyroid cancer progression by regulating anoikis resistance.","authors":"Zhang S; Gu X; Zhai X; Huang H; Zhang R; Ye H","abstract":"FN1 is an anoikis-related hub gene in thyroid cancer. FN1 highly expressed in PTC and associated with poor prognosis. Silencing FN1 inhibited proliferation, migration, invasion and increased anoikis; overexpression opposite. FN1 up-regulates anti-apoptotic BCL2L1 and down-regulates pro-apoptotic BAD, enhancing anoikis resistance. FN1 may act as a therapeutic target for advanced PTC.","doi":"10.1038/s41598-026-43495-8","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42002564/","source_queries":["b"],"in_scope":True,"relevance":"High","dimensions":["molecular"]},
 {"paper_id":"42008746","title":"PRECISE: A Prognostic Thyrocyte-Derived Gene Signature for Papillary Thyroid Carcinoma.","authors":"Li S; Wu CC; Marczyk VR; Loberg MA; Thennavan A; Tarabichi M; Xu L; Henderson YC; Martin ME; Tran TM; Duose DY; Sanchez-Espitia A; Luthra R; Sheng Q; Xu GJ; Huang EC; Hofmann MC; Zhao X; Lai SY; Hosseini SM; Williams MD; Wang W; Hamidi S; Zafereo ME; Cabanillas ME; Navin NE; Weiss VL; Wang JR","abstract":"PRECISE (Prognostic RNA Expression Cell-specific Integrated Signature) developed using scRNA-seq/snRNA-seq, evaluated across MDACC (n=109), VUMC (n=65), TCGA (n=370). 41 epithelial genes downregulated in PTC tumor cells. Higher PRECISE associated with shorter PFS in all three cohorts (MDACC HR=1.64; VUMC HR=2.54; TCGA HR=1.63) and remained significant after stage adjustment in two cohorts. Also associated with DSS (MDACC HR=4.16; VUMC HR=2.23). Incorporating PRECISE improved predictive performance beyond stage-based models. A thyroid epithelial gene signature with independent prognostic value in PTC.","doi":"10.1158/1078-0432.CCR-25-4488","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42008746/","source_queries":["e"],"in_scope":True,"relevance":"High","dimensions":["single-cell","prognosis","molecular"]},
 {"paper_id":"42031943","title":"Deep learning-based multimodal radiopathomics for preoperative prediction of lymph node metastasis in papillary thyroid carcinoma.","authors":"Cai Q; Gao T; Zhou L; Zhang S; Chen Y; Xu X; Jiang TA; Zhang J; Zhang X; Feng Z; You Q","abstract":"1095 FNA liquid-based cytology specimens + 2190 ultrasound images. ResNet-101 five-fold cross-validation, validated on two external centers. Multimodal model AUC 0.891 internal / 0.875 external, outperformed ultrasound- or cytology-only. Gradient-weighted CAM revealed nuclear features most influential. Potential to guide clinical decision-making, reduce unnecessary LND.","doi":"10.1038/s41598-026-48693-y","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42031943/","source_queries":["c"],"in_scope":True,"relevance":"High","dimensions":["algorithm"]},
 {"paper_id":"42131580","title":"Tumor-Derived Exosomal PDLIM1 Promotes Angiogenesis and Tumor Progression in Papillary Thyroid Carcinoma: Insights From Integrated Single-Cell Transcriptomics and Exosomal Proteomics.","authors":"Qiu W; Yan T; Huang X; Fan Y; Di J; Yang Z","abstract":"scRNA-seq on primary and metastatic PTC (n=12 samples, 4 patients). Scissor+ cells linked to metastatic phenotypes; VEGF signaling upregulated. Among 6 exosomal proteins, PDLIM1 highly expressed in PTC cell lines and metastatic tissues. Tumor-derived exosomal PDLIM1 internalized by endothelial cells, enhancing angiogenesis in vitro; knockdown suppressed tube formation and reduced tumor volume, CD31+ microvessel, LYVE-1+ lymphatic density in xenografts. Exosomal PDLIM1 promotes angiogenesis and primary tumor progression in PTC.","doi":"10.2147/CMAR.S589372","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42131580/","source_queries":["e"],"in_scope":True,"relevance":"Medium","dimensions":["single-cell","molecular","immune"]},
 {"paper_id":"42134246","title":"Transcriptomic sequencing analysis of the tumor microenvironment atlas and potential mechanisms of metastasis in papillary thyroid carcinoma.","authors":"An H; Zhang W; Niu H; Liang W; Lv B; Wu S; Xu L; Li W; Gao S","abstract":"Integrated scRNA-seq from tumor (T), peritumoral thyroid (PT) and lymph-node (LN) with bulk transcriptomes. Metastatic (M) vs non-metastatic (NM). NK and CD4+TNFRSF4 cells enriched in M; Mac-APOC1 M2-like TAM; RGS5+ myCAFs expanded in M from T and LN, up-regulating metabolic/ribosomal pathways. Random-forest classifier 0.98 accuracy for N-stage; lasso-Cox signature (C-index >0.9) stratified survival. Reveals cellular/functional heterogeneity driving PTC progression and metastasis-associated subpopulations.","doi":"10.1016/j.molimm.2026.05.006","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42134246/","source_queries":["d","e"],"in_scope":True,"relevance":"High","dimensions":["single-cell","immune","algorithm","molecular"]},
 {"paper_id":"42185182","title":"Prediction and Clinical Application of Central Lymph Node Metastasis in Papillary Thyroid Carcinoma Based on Multi-modal Ultrasound Feature Fusion: A Multi-center Study.","authors":"Huang Y; Dong X; Gao L; Wang C; Deng X; Chu X; Li Y; Zhou W; Chen M; Wang T; Li H; Chen Y","abstract":"568 PTC patients from 4 hospitals. BMUS + strain elastography (SE) deep features via EfficientNet-B4, fused. Internal validation AUC 0.929 (BMUS 0.843, SE 0.875); external test AUC 0.843. Outperformed all individual radiologists (AUC 0.585-0.649); AI assistance improved radiologists (AUC 0.701-0.752). Multi-modal DL enables accurate interpretable preoperative CLNM prediction, robust across centers.","doi":"10.1016/j.ultrasmedbio.2026.04.024","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42185182/","source_queries":["c"],"in_scope":True,"relevance":"High","dimensions":["algorithm"]},
 {"paper_id":"42244944","title":"Bilateral disease in the classic subtype of papillary thyroid carcinoma: clinical significance and development of an artificial intelligence-based multimodal prediction model.","authors":"Wu WX; Yang YX; Feng JW; Liu SQ; Qin AC; Jiang Y","abstract":"1218 PTC patients. 26.1% multifocal, 62.7% of those bilateral. Bilateral disease associated with larger tumor, higher LNM, worse RFS; independent recurrence risk (HR=9.664). Integrated Model D (LASSO + TresNet) AUC 0.970 training / 0.932 validation / 0.848 external. Improved diagnostic accuracy across radiologist levels. Bilateral disease, not multifocality alone, is significant recurrence risk; AI model predicts it preoperatively.","doi":"10.3389/fendo.2026.1759451","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42244944/","source_queries":["c"],"in_scope":True,"relevance":"High","dimensions":["algorithm","prognosis"]},
 {"paper_id":"42301557","title":"DLEU2 promotes the migration and invasion of papillary thyroid carcinoma cells through the ELAVL1/RCC2 axis.","authors":"Zuo S; Sun S; Wang Y; Song J; Zhou Y; Liu S; Xue G; Lin X; Wu JF","abstract":"LncRNA DLEU2 aberrantly expressed in PTC, relevant to tumorigenesis and lymphatic metastasis. DLEU2 facilitates migration/invasion. ELAVL1 binds and stabilizes m6A-modified RCC2 mRNA. Rescue experiments identified DLEU2-ELAVL1-RCC2 axis functioning via Wnt5a/beta-catenin to support EMT and enhance migration/invasion. Elucidates mechanism and possible molecular target for PTC.","doi":"10.1007/s10142-026-01936-7","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42301557/","source_queries":["b"],"in_scope":True,"relevance":"High","dimensions":["molecular"]},
 {"paper_id":"42305510","title":"Identification and validation of tumor microenvironment remodeling markers associated with prognosis in differentiated thyroid cancer.","authors":"Liu X; Ma Q; Su D; Li Y; Zeng X; Guo L","abstract":"Tumor microenvironment remodeling (TER) important in DTC progression/invasion/metastasis. Consensus clustering grouped DTC into subtypes. After evaluating 101 ML models, random survival forest and Ridge identified 5 key signatures (CAMP, DDIT4L, LMX1B, NAT16, CALN1). AUCs 0.96/0.99/1.00 for 1-/2-/3-year survival. CALN1 upregulated in DTC; others downregulated. Comprehensive evaluation of prognostic significance of TERRGs.","doi":"10.21037/tcr-2026-1-0208","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42305510/","source_queries":["b"],"in_scope":True,"relevance":"High","dimensions":["molecular","immune","prognosis"]},
 {"paper_id":"42329337","title":"Integrated bulk and single-cell RNA sequencing reveals a prognostic neuro-mimicry signature in papillary thyroid carcinoma.","authors":"Liu X; Mei C; Tan J; Liu Y; Liu Y; Zhou Z; Zhao J","abstract":"521 PTC patients TCGA. Neuron-specific gene set screened; 8-gene signature (KCNN4, KCNN1, KCNT2, SNAP25, KCNK16, GABRG1, GABRG2, GABRB2) via LASSO. AUC 0.721 for LNM. scRNA-seq (GSE184362, 65,744 cells) confirmed GABRB2 enriched in malignant thyrocytes 200x vs immune. High-risk patients showed immunosuppressive features. Targeting ion channels may modulate neuro-immune interactions in thyroid cancer.","doi":"10.1007/s12672-026-05278-5","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42329337/","source_queries":["e"],"in_scope":True,"relevance":"Medium","dimensions":["single-cell","molecular","prognosis"]},
 {"paper_id":"42332350","title":"[Methyltransferase-like protein 7B promotes glycolysis and malignant progression in papillary thyroid carcinoma cells via the USP28/HIF-1alpha axis].","authors":"Xu F; Xie Q","abstract":"METTL7B significantly upregulated in PTC and positively correlated with lymph node metastasis. Knockdown suppressed proliferation, colony formation, xenograft growth. METTL7B inhibited ubiquitination/degradation of HIF-1alpha, mediated by USP28. METTL7B enhanced glycolytic activity and malignant phenotypes via USP28/HIF-1alpha axis. METTL7B promotes glycolysis and malignant progression in PTC by stabilizing HIF-1alpha through USP28-mediated deubiquitination.","doi":"10.3724/zdxbyxb-2025-0822","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42332350/","source_queries":["i"],"in_scope":True,"relevance":"High","dimensions":["metabolic","molecular"]},
 {"paper_id":"42351648","title":"FOXP Transcription Factors in Thyroid Cancer: From Molecular Expression to Clinical Significance.","authors":"Vasiljevic T; Kokanov NS; Kozik B","abstract":"Review of FOXP1-FOXP4 in thyroid cancer. FOXP3 and FOXP4 associated with aggressive features (ETE, LNM, distant mets), poor prognosis. FOXP3 contributes to immune evasion and RAI resistance via NIS suppression. FOXP4 activates oncogenic pathways and non-coding RNAs. FOXP2 mainly tumor suppressor. FOXP family promising diagnostic/prognostic/therapeutic biomarkers, needs validation in large cohorts.","doi":"10.3390/biomedicines14061222","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42351648/","source_queries":["b"],"in_scope":True,"relevance":"Medium","dimensions":["molecular","immune"]},
 {"paper_id":"42353188","title":"Targeting the Warburg Effect in Anaplastic Thyroid Carcinoma: Metabolic Vulnerabilities and Therapeutic Opportunities.","authors":"Iova OM; Marin GE; Razniceanu V; Mocrei-Rebrean SM; Pintilie SR; Netea-Maier RT; Berindan-Neagoe I","abstract":"Review synthesizing evidence on Warburg effect in ATC/PDTC. BRAF, RAS, TP53 mutations and PI3K/AKT/mTOR, HIF-1alpha converge to promote glycolytic reprogramming, supporting proliferation, immune evasion, metastasis via glucose uptake, lactate, microenvironment remodeling. Glucose transporters, hexokinase, monocarboxylate transporters as targets. Preclinical inhibition reduces growth, enhances radiosensitivity. Future: combination therapies, biomarker-driven stratification.","doi":"10.3390/ijms27125472","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42353188/","source_queries":["i"],"in_scope":True,"relevance":"Medium","dimensions":["metabolic"]},
 {"paper_id":"42397917","title":"Single-cell transcriptomic analysis reveals tumor-immune determinants of lymph node colonization and progression in thyroid cancer.","authors":"Nguyen AT; Viramontes J; Vazquez I; McWilliam C; Devarakonda V; Henson R; Sacks WL; Mallen-St Clair J; Chen Y; Walgama E; Scher KS; Moyers J; Sandler HM; Jang JK; Zumsteg ZS; Shon W; Shiao SL; Ho AS","abstract":"Isolated tumor-infiltrating leukocytes from primary thyroid tumors and matched metastatic LNs for scRNA-seq + multiplex IHC. Thyrocytes and TAMs down-regulate TNFRSF12A and CX3CR1 upon LN colonization. LNs induced Treg to suppress T-cell cytotoxicity. TILs in LNs showed increased IL7R. High LN IL7R correlated with improved outcomes, biomarker in heterogeneous disease. Dynamic equilibrium within LN metastases may offer conserved nodal colonization mechanisms.","doi":"10.1126/sciadv.aea4727","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42397917/","source_queries":["d","e"],"in_scope":True,"relevance":"High","dimensions":["single-cell","immune"]},
 {"paper_id":"42430190","title":"Single-cell sequencing profiling of intratumoral heterogeneity and immunosuppressive microenvironment in primary thyroid cancer and lymph node metastases.","authors":"Xu S; Su Y; Zhang S; Huang D; Wu S; Song C; Zhong W; Xie L; Chen W","abstract":"55,005 single cells from paired primary tumors and LNs. cNMF revealed malignant epithelial heterogeneity and metastatic trajectories. Metastatic niche enriched FOXP3+ Treg, LAMP3+ DCs, CCL18+ M2-like macrophages. Canonical PD-1/PD-L1/2 minimal; LAG3-LGALS3 axis identified as dominant immune evasion pathway between CD8+ T cells and stroma. Challenges utility of conventional PD-1 blockade; rationale for next-gen immunotherapeutic strategies. Limited by modest sample size.","doi":"10.1080/2162402X.2026.2701504","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42430190/","source_queries":["d","e"],"in_scope":True,"relevance":"High","dimensions":["single-cell","immune"]},
 {"paper_id":"42433575","title":"Enhancing BRAF V600E mutation prediction in thyroid cancer through interpretable deep learning models combining clinical and ultrasound-based radiomics features.","authors":"Zhang L; Huang C; Chen Z; Ying Y; Jiang N; Zhong X; Chen F; Guo Y; Luo S","abstract":"1202 patients, 6703 US images. XGBoost best ML (AUC 0.809 train/0.745 test lesion-level). ResNet50 DL AUC 0.807 test. Combined model AUC 0.845 train/0.814 test. SHAP revealed DL scores and radscores key contributors. Combined model integrating clinical and US data effectively predicts BRAF V600E status non-invasively.","doi":"10.21037/qims-2026-1-0299","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/42433575/","source_queries":["c"],"in_scope":True,"relevance":"High","dimensions":["algorithm","molecular"]},
 {"paper_id":"41539369","title":"circPTPRM can encode a functional polypeptide circPTPRM-187aa to promote papillary thyroid carcinoma progression.","authors":"Lv C; Huang J; Ji X; Sun W; Zhang H","abstract":"circPTPRM influences PTC proliferation, migration, invasion via translated polypeptide. Overexpression increased tumor volume/weight in vivo. circPTPRM-187aa binds IQGAP1 and induces TGF-beta pathway activation by elevating RAC1 and CDC42. circPTPRM encodes circPTPRM-187aa regulating IQGAP1, up-regulating RAC1/CDC42 in TGF-beta signaling, enhancing PTC progression.","doi":"10.1016/j.mce.2026.112734","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41539369/","source_queries":["b"],"in_scope":True,"relevance":"High","dimensions":["molecular"]},
 {"paper_id":"41510756","title":"Programmed death-ligand 1 expression is associated with local invasion and distant metastases in differentiated thyroid cancer: Systematic review and meta-analysis.","authors":"Mediratta RK; Bernstein I; Zheng C; Schmidt C; Ganti AK; Band H; Bennett RG; Kotwal A","abstract":"Meta-analysis of 12 retrospective DTC studies. High PD-L1 associated with LVI (OR 4.2), ETE (OR 1.7, p=0.005) and distant metastases (OR 4.6, p=0.004). No significant association with tumor size, multifocality, LNM, AJCC stage, recurrence, or disease-specific mortality. PD-L1 overexpression in DTC associated with higher risk of local invasion and distant metastases via immune evasion.","doi":"10.1177/10815589261415900","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41510756/","source_queries":["g"],"in_scope":True,"relevance":"High","dimensions":["immune","prognosis"]},
 {"paper_id":"41514331","title":"The dual oncogenic and protective roles of hashimoto's thyroiditis in papillary thyroid carcinoma: a cohort-based meta-analysis.","authors":"Ma X; Shang H; Zhang Y; Xia Z","abstract":"Meta-analysis (PROSPERO) of 41 studies, 67,901 patients. HT associated with increased multifocality (OR 1.13) and bilaterality (OR 1.20), reduced ETE (0.85), capsular invasion (0.73), central LNM (0.75), distant metastasis (0.33), recurrence (0.74). No difference for vascular invasion, lateral LNM, mortality, RAI. HT associated with reduced BRAF V600E (0.55). HT dual role: promotes multifocality while attenuating aggressiveness.","doi":"10.1186/s12957-025-04184-4","published_date":"2026-01-01","url":"https://pubmed.ncbi.nlm.nih.gov/41514331/","source_queries":["g"],"in_scope":True,"relevance":"Medium","dimensions":["prognosis","immune"]},
]

# ---- Newly surfaced OFF-TOPIC (excluded) papers this run (compact; PMID+title) ----
new_offtopic = [
 ("42321032","Retraction notice to 'Decoding tumor microenvironment: EMT modulation in breast cancer metastasis...'"),
 ("42500581","The Intratumoral Microbiota in Breast Cancer"),
 ("42500577","Tumour-Derived sEVs Promote TNBC Progression Associated with HAVCR2 Upregulation in Macrophages"),
 ("42464297","The NLRP3 inflammasome in gastrointestinal malignancies"),
 ("42488653","Heterogeneity of ICI-related inflammatory CNS irAE reporting signals"),
 ("42409802","Intratumoral microbiota in tumorigenesis: A double-edged sword"),
 ("42373805","DNA methylation-mediated silencing of STAT5A drives breast cancer metastasis"),
 ("42310731","Plasma proteome-metabolome signatures enable BC early detection and LN risk"),
 ("41874611","Decoding CXC chemokines in pulmonary metastasis of colorectal cancer"),
 ("42291329","The dialogue between breast cancer and microorganisms"),
 ("42273688","Regulatory T cells in breast cancer"),
 ("42373830","Multi-omics reveals TME heterogeneity in peritoneal metastasis of gastric cancer"),
 ("41608657","Breast cancer stem cell activity driven by ME18D in the TME"),
 ("41129052","Fibroblasts in the TME: heterogeneity revealed by spatial transcriptomics"),
 ("39923580","Pan-cancer examination of transcription factor MAFF"),
 ("42067069","EWSR1-rearranged renal neoplasia"),
 ("42436124","Single-cell multi-omics deciphers myofibro-inflammatory program of CAFs in TNBC"),
 ("42050078","Olfactomedin 4 orchestrates TGF-beta/CEACAM6 axis in gallbladder carcinogenesis"),
 ("40665712","Keratin 6A Overexpression promotes progression of TNBC"),
 ("42271337","FGD3 as prognostic and immunological biomarker: pan-cancer analysis"),
 ("41759425","Saikosaponin D inhibits gastric cancer via PKM2-mediated glycolysis"),
 ("41855762","Pseudoginsenoside F11 enhances YBX1-mediated repression of PRPS2 in TNBC"),
 ("41974658","Oncoprotein CYB561 promotes breast cancer lipogenesis"),
 ("41679436","Cuproptosis and anti-metastatic immunity in breast cancer via lactate reprogramming"),
 ("41690034","Curcumol targets ATG4B-PKM2-lactate axis in colorectal cancer liver metastasis"),
 ("41814323","PKM2 phosphorylation by c-SRC activates glycolysis in colon cancer"),
 ("41435694","HNRNPC lactylation promotes pancreatic cancer via PAK6 splicing"),
 ("41513216","lncRNA SENCR drives breast cancer via miR-3648/FOXD3 axis"),
 ("42343437","FBXO5 regulates RPL23A to promote breast cancer progression"),
 ("42330341","Neuron-Derived MIF Engages VCAM1 in gastric cancer PNI and metastasis"),
 ("42237330","TRIM71 suppresses cervical cancer via Nectin4/Wnt-beta-catenin"),
 ("42222424","Methylation-regulated miR-374a/b suppress glycolysis in HNSCC"),
 ("41049154","ML models predict prognosis of breast cancer LN mets after NAC"),
 ("33186350","Nucleotide de novo synthesis increases breast cancer stemness and metastasis"),
 ("39296076","ML AR regulatory gene random forest model in prostate cancer"),
 ("38218916","Surgical margins and prognosis of borderline/malignant phyllodes tumors"),
 ("37851243","BRAF V600E in PTMC intermediate-high recurrence risk after RAI"),
 ("38311812","Pregnancy and disease recurrence of DTC: systematic review and meta-analysis"),
 ("41759361","Distant recurrence in breast cancer after pCR to NAC"),
 ("41488288","Organ-specific features of post-relapse survival in metastatic breast cancer"),
 ("41815549","AI ultrasound radiomics prognostic model for TNBC"),
]

# Build merged record list
merged = list(base_records)  # 106
added_inscope = 0
for r in new_inscope:
    if r["paper_id"] not in base_pmids:
        merged.append(r); added_inscope += 1
added_off = 0
for pid, title in new_offtopic:
    if pid not in base_pmids:
        merged.append({"paper_id":pid,"title":title,"authors":"","abstract":"","doi":"","published_date":"2026-01-01","url":f"https://pubmed.ncbi.nlm.nih.gov/{pid}/","source_queries":["x"],"in_scope":False,"relevance":"Excluded","dimensions":[]})
        added_off += 1

# Normalize dimension labels (base used 'singlecell' without hyphen)
DIM_MAP = {"singlecell":"single-cell"}
for r in merged:
    if "dimensions" in r and isinstance(r["dimensions"], list):
        r["dimensions"] = [DIM_MAP.get(x, x) for x in r["dimensions"]]

# Stats
all_pmids = [ (r.get("paper_id") or r.get("pmid")) for r in merged ]
unique = len(set(all_pmids))
inscope = [r for r in merged if r.get("in_scope")]
excluded = [r for r in merged if not r.get("in_scope")]

# Dimension distribution (multi-tag)
dims = ["molecular","immune","single-cell","spatial","algorithm","prognosis","metabolic"]
dim_count = {d:0 for d in dims}
for r in inscope:
    for d in r.get("dimensions",[]):
        if d in dim_count: dim_count[d]+=1

new_inscope_pmids = [r["paper_id"] for r in new_inscope]

corpus_delta = {
  "new_in_scope_count": added_inscope,
  "new_in_scope_pmids": new_inscope_pmids,
  "new_excluded_offtopic_count": added_off,
  "new_excluded_offtopic_pmids": [p for p,_ in new_offtopic if p not in base_pmids],
  "baseline_run5_unique": len(base_records),
  "baseline_run5_in_scope": len(base_inscope),
  "cumulative_unique": unique,
  "cumulative_in_scope": len(inscope),
  "note": "Run#5 plateau (106 unique / 70 in-scope, 0 new) was an artifact of sort=relevance always returning the same top-15. Run#6 switched to sort=pub_date recency sweep across all 9 queries, revealing 32 previously-uncaptured in-scope thyroid papers (mostly 2025-2026). 45 run#5 in-scope papers not re-surfaced by the pub_date sweep are RETAINED in the cumulative corpus for continuity."
}

out = {
  "search_date": datetime.date.today().isoformat(),
  "run": "run#6",
  "source": "mcp__paper-search-mcp__search_pubmed (DeferExecuteTool); max_results=15; sort=pub_date (recency sweep)",
  "queries": {
    "a":"thyroid cancer lymph node metastasis biomarker gene signature",
    "b":"thyroid cancer invasion metastasis molecular mechanism",
    "c":"thyroid cancer lymph node metastasis machine learning deep learning prediction model",
    "d":"thyroid cancer metastasis tumor immune microenvironment",
    "e":"thyroid cancer metastasis single cell RNA sequencing",
    "f":"thyroid cancer metastasis spatial transcriptomics spatial multi-omics",
    "g":"thyroid cancer prognosis recurrence distant metastasis risk model",
    "h":"thyroid cancer metastatic stemness subpopulation",
    "i":"thyroid cancer metabolic reprogramming metastasis"
  },
  "raw_count": 114,
  "unique_count": unique,
  "in_scope_count": len(inscope),
  "excluded_count": len(excluded),
  "dimension_distribution_in_scope": dim_count,
  "corpus_delta_vs_run5": corpus_delta,
  "records": merged
}

with open("search_results_latest.json","w",encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("MERGED unique:", unique, "| in-scope:", len(inscope), "| excluded:", len(excluded))
print("Added in-scope:", added_inscope, "| Added off-topic:", added_off)
print("Dimension distribution (in-scope, multi-tag):")
for d,c in dim_count.items(): print(f"  {d}: {c}")
print("New in-scope PMIDs:", new_inscope_pmids)
